2. Data reduction

In [7]:

#* import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:

#? load datasets
brent_oil = pd.read_csv('C:/Users/anasq\OneDrive/Desktop/PetroAnalyst/Dataset/brent_oil_price.csv')
wti_oil = pd.read_csv('C:/Users/anasq/OneDrive/Desktop/PetroAnalyst/Dataset/wti_crude_oil_price.csv')
lpg_price_india = pd.read_csv('C:/Users/anasq/OneDrive/Desktop/PetroAnalyst/Dataset/india_lpg_price_delhi_2010_2026.csv')
fuel_price_india = pd.read_csv('C:/Users/anasq/OneDrive/Desktop/PetroAnalyst/Dataset/petrol_diesel_prices.csv')

GPR_index = pd.read_csv('C:/Users/anasq/OneDrive/Desktop/PetroAnalyst/Dataset/older data/data_gpr_export.csv')
INR_to_USD = pd.read_csv('C:/Users/anasq/OneDrive/Desktop/PetroAnalyst/Dataset/INR_to_USD.csv')

<>:2: SyntaxWarning: invalid escape sequence '\O'
<>:2: SyntaxWarning: invalid escape sequence '\O'
C:\Users\anasq\AppData\Local\Temp\ipykernel_9228\1910678201.py:2: SyntaxWarning: invalid escape sequence '\O'
  brent_oil = pd.read_csv('C:/Users/anasq\OneDrive/Desktop/PetroAnalyst/Dataset/brent_oil_price.csv')

In [9]:

#^ reduce all irrelevant colm from grp dataset

#~ before reduction
for col in GPR_index.columns:
    print(col)

date
GPR
GPRT
GPRA
GPRH
GPRHT
GPRHA
SHARE_GPR
N10
SHARE_GPRH
N3H
GPRH_NOEW
GPR_NOEW
GPRH_AND
GPR_AND
GPRH_BASIC
GPR_BASIC
SHAREH_CAT_1
SHAREH_CAT_2
SHAREH_CAT_3
SHAREH_CAT_4
SHAREH_CAT_5
SHAREH_CAT_6
SHAREH_CAT_7
SHAREH_CAT_8
GPRC_ARG
GPRC_AUS
GPRC_BEL
GPRC_BRA
GPRC_CAN
GPRC_CHE
GPRC_CHL
GPRC_CHN
GPRC_COL
GPRC_DEU
GPRC_DNK
GPRC_EGY
GPRC_ESP
GPRC_FIN
GPRC_FRA
GPRC_GBR
GPRC_HKG
GPRC_HUN
GPRC_IDN
GPRC_IND
GPRC_ISR
GPRC_ITA
GPRC_JPN
GPRC_KOR
GPRC_MEX
GPRC_MYS
GPRC_NLD
GPRC_NOR
GPRC_PER
GPRC_PHL
GPRC_POL
GPRC_PRT
GPRC_RUS
GPRC_SAU
GPRC_SWE
GPRC_THA
GPRC_TUN
GPRC_TUR
GPRC_TWN
GPRC_UKR
GPRC_USA
GPRC_VEN
GPRC_VNM
GPRC_ZAF
GPRHC_ARG
GPRHC_AUS
GPRHC_BEL
GPRHC_BRA
GPRHC_CAN
GPRHC_CHE
GPRHC_CHL
GPRHC_CHN
GPRHC_COL
GPRHC_DEU
GPRHC_DNK
GPRHC_EGY
GPRHC_ESP
GPRHC_FIN
GPRHC_FRA
GPRHC_GBR
GPRHC_HKG
GPRHC_HUN
GPRHC_IDN
GPRHC_IND
GPRHC_ISR
GPRHC_ITA
GPRHC_JPN
GPRHC_KOR
GPRHC_MEX
GPRHC_MYS
GPRHC_NLD
GPRHC_NOR
GPRHC_PER
GPRHC_PHL
GPRHC_POL
GPRHC_PRT
GPRHC_RUS
GPRHC_SAU
GPRHC_SWE
GPRHC_THA
GPRHC_TUN
GPRHC_TUR
GPRHC_TWN
GPRHC_UKR
GPRHC_USA
GPRHC_VEN
GPRHC_VNM
GPRHC_ZAF
var_name
var_label

In [10]:
GPR_index = GPR_index[['date', 'GPR']]

In [11]:

#& after reduction
GPR_index

            date     GPR
0     12/31/1899     NaN
1      1/31/1900     NaN
2       3/1/1900     NaN
3       4/1/1900     NaN
4       5/1/1900     NaN
...          ...     ...
1510   11/1/2025  104.34
1511   12/1/2025  131.39
1512    1/1/2026  167.80
1513    2/1/2026  121.62
1514    3/1/2026  297.27

[1515 rows x 2 columns]

In [12]:

#todo data between jan-2010 to mar-2026
# Select rows 1320 through 1514
GPR_index = GPR_index.iloc[1320:1515]

In [13]:

#* final GPR dataset
GPR_index.to_csv

<bound method NDFrame.to_csv of            date     GPR
1320   1/1/2010   91.58
1321   2/1/2010   80.73
1322   3/1/2010   74.12
1323   4/1/2010   88.76
1324   5/1/2010   88.96
...         ...     ...
1510  11/1/2025  104.34
1511  12/1/2025  131.39
1512   1/1/2026  167.80
1513   2/1/2026  121.62
1514   3/1/2026  297.27

[195 rows x 2 columns]>

In [14]:

#* new csv file
GPR_index.to_csv('reduced_gpr.csv', index=False)

In [15]:

#todo reduce colm from lpg dataset

lpg_price_india = lpg_price_india[['date','delhi_price','mumbai_price','kolkata_price','chennai_price','bengaluru_price']]

In [16]:

#^ add average price colm
cities = ['delhi_price','mumbai_price','kolkata_price','chennai_price','bengaluru_price']

lpg_price_india['avg_price'] = lpg_price_india[cities].mean(axis=1)

In [17]:
lpg_price_india

,date,delhi_price,mumbai_price,kolkata_price,chennai_price,bengaluru_price,avg_price
0,01-01-2010,350.0,345.0,365.0,355.0,352.0,353.4
1,01-02-2010,350.0,345.0,365.0,355.0,352.0,353.4
2,01-03-2010,355.0,350.0,370.0,360.0,357.0,358.4
3,01-04-2010,360.0,355.0,375.0,365.0,362.0,363.4
4,01-05-2010,365.0,360.0,380.0,370.0,367.0,368.4
...,...,...,...,...,...,...,...
190,01-11-2025,853.0,852.5,879.0,868.5,855.5,861.7
191,01-12-2025,853.0,852.5,879.0,868.5,855.5,861.7
192,01-01-2026,853.0,852.5,879.0,868.5,855.5,861.7
193,01-02-2026,853.0,852.5,879.0,868.5,855.5,861.7
194,01-03-2026,913.0,912.5,939.0,928.5,915.5,921.7

In [18]:
fuel_price_india = fuel_price_india[['date', 'delhi_petrol', 'delhi_diesel', 'mumbai_petrol','mumbai_diesel', 'kolkata_petrol', 'kolkata_diesel', 'chennai_petrol', 'chennai_diesel', 'bengaluru_petrol', 'bengaluru_diesel']]

In [19]:

#? add avg price colm for petrol and diesel

petrol_cities = ['delhi_petrol', 'mumbai_petrol', 'kolkata_petrol', 'chennai_petrol', 'bengaluru_petrol']
diesel_cities = ['delhi_diesel', 'mumbai_diesel', 'kolkata_diesel', 'chennai_diesel', 'bengaluru_diesel']

fuel_price_india['avg_petrol'] = fuel_price_india[petrol_cities].mean(axis=1).round(2)
fuel_price_india['avg_diesel'] = fuel_price_india[diesel_cities].mean(axis=1).round(2)

In [20]:
fuel_price_india

,date,delhi_petrol,delhi_diesel,mumbai_petrol,mumbai_diesel,kolkata_petrol,kolkata_diesel,chennai_petrol,chennai_diesel,bengaluru_petrol,bengaluru_diesel,avg_petrol,avg_diesel
0,01-01-2010,47.93,38.10,51.67,40.50,52.20,41.00,52.13,40.80,50.50,39.80,50.89,40.04
1,01-02-2010,47.43,35.47,51.15,37.80,51.68,38.20,51.59,37.90,49.90,37.20,50.35,37.31
2,01-03-2010,47.93,38.10,51.67,40.50,52.20,41.00,52.13,40.80,50.50,39.80,50.89,40.04
3,01-04-2010,47.93,38.10,51.67,40.50,52.20,41.00,52.13,40.80,50.50,39.80,50.89,40.04
4,01-05-2010,48.50,38.50,52.20,41.00,52.80,41.50,52.70,41.30,51.00,40.20,51.44,40.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,01-11-2025,105.01,95.00,112.00,98.00,112.80,97.50,111.50,98.20,110.00,96.50,110.26,97.04
191,01-12-2025,105.01,95.00,112.00,98.00,112.80,97.50,111.50,98.20,110.00,96.50,110.26,97.04
192,01-01-2026,102.00,92.00,109.00,95.00,109.80,94.50,108.50,95.20,107.00,93.50,107.26,94.04
193,01-02-2026,102.00,92.00,109.00,95.00,109.80,94.50,108.50,95.20,107.00,93.50,107.26,94.04
194,01-03-2026,94.77,87.67,103.54,90.03,105.45,92.02,100.84,92.39,102.92,90.99,101.50,90.62

In [22]:
fuel_price_india.to_csv('updated_fuel_price.csv')
lpg_price_india.to_csv('updated_lpg_price.csv')